/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab8PL;

import java.awt.Point;

/**
 *
 * @author Costinel
 */
public class Lab9Frame extends javax.swing.JFrame {

    /**
     * Creates new form Lab9Frame
     */
    public Lab9Frame() {
        initComponents();
        
        model = new MapGameModel();
        
        this.updateViewWithPosition();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapPanel = new Lab8PL.MapPanelView();
        northBtn = new javax.swing.JButton();
        southBtn = new javax.swing.JButton();
        eastBtn = new javax.swing.JButton();
        westBtn = new javax.swing.JButton();
        teleportBtn = new javax.swing.JButton();
        startBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout mapPanelLayout = new javax.swing.GroupLayout(mapPanel);
        mapPanel.setLayout(mapPanelLayout);
        mapPanelLayout.setHorizontalGroup(
            mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );
        mapPanelLayout.setVerticalGroup(
            mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        northBtn.setText("Move North");
        northBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                northBtnMouseClicked(evt);
            }
        });

        southBtn.setText("Move South");
        southBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                southBtnMouseClicked(evt);
            }
        });

        eastBtn.setText("Move East");
        eastBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eastBtnMouseClicked(evt);
            }
        });

        westBtn.setText("Move West");
        westBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                westBtnMouseClicked(evt);
            }
        });

        teleportBtn.setText("Teleport");
        teleportBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teleportBtnMouseClicked(evt);
            }
        });

        startBtn.setText("Start/Restart");
        startBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mapPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(westBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(teleportBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(eastBtn)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startBtn)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(northBtn)
                                .addComponent(southBtn)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mapPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(northBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(southBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(westBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eastBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(teleportBtn))))
                        .addGap(41, 41, 41)
                        .addComponent(startBtn)
                        .addGap(0, 192, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void northBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_northBtnMouseClicked
        // TODO add your handling code here:
        
        if(this.model.moveNorth())
        {
            this.updateViewWithPosition();
        }
        
        
    }//GEN-LAST:event_northBtnMouseClicked

    private void startBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startBtnMouseClicked
        // TODO add your handling code here:
        
        if(this.model.start())
        {
            this.updateViewWithPosition();
        }
        
    }//GEN-LAST:event_startBtnMouseClicked

    private void westBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_westBtnMouseClicked
        // TODO add your handling code here:
        
        this.model.moveWest();
        this.updateViewWithPosition();
    }//GEN-LAST:event_westBtnMouseClicked

    private void southBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_southBtnMouseClicked
        // TODO add your handling code here:
        
        this.model.moveSouth();
        this.updateViewWithPosition();
        
    }//GEN-LAST:event_southBtnMouseClicked

    private void eastBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eastBtnMouseClicked
        // TODO add your handling code here:
        
        this.model.moveEast();
        this.updateViewWithPosition();
        
    }//GEN-LAST:event_eastBtnMouseClicked

    private void teleportBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teleportBtnMouseClicked
        // TODO add your handling code here:
        
        this.model.teleport();
        this.updateViewWithPosition();
        
    }//GEN-LAST:event_teleportBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab9Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab9Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab9Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab9Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab9Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eastBtn;
    private Lab8PL.MapPanelView mapPanel;
    private javax.swing.JButton northBtn;
    private javax.swing.JButton southBtn;
    private javax.swing.JButton startBtn;
    private javax.swing.JButton teleportBtn;
    private javax.swing.JButton westBtn;
    // End of variables declaration//GEN-END:variables

    MapGameModel model;

    
    private void updateViewWithPosition()
    {
        int line = this.model.getCurrentLine();
        int col = this.model.getCurrentColumn();
        
        this.mapPanel.setCurrentPoint(new Point(line-1, col-1));
        this.mapPanel.repaint();
    }
    
}
