/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.PA.Views;
import com.PA.MovieCatalog.*;
import java.util.*;

/**
 *
 * @author Costinel
 */
public class InfoPanel extends javax.swing.JPanel {

    /**
     * Creates new form InfoPanel
     */
    public InfoPanel() {
        initComponents();
    }
    
    public void displayInfoForMovie(Movie m)
    {
        this.movieListPanel.setVisible(false);
        this.movieInfoPanel.setVisible(true);
        this.movieInfoPanel.displayInfoForMovie(m);
    }
    
    public void displayInfoForMovieList(List<Movie> movieList)
    {
        this.movieInfoPanel.setVisible(false);
        this.movieListPanel.setVisible(true);
        this.movieListPanel.displayMovieList(movieList);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        movieInfoPanel = new com.PA.Views.MovieInfoPanel();
        movieListPanel = new com.PA.Views.MovieListPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(movieInfoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, -1));
        add(movieListPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 366));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.PA.Views.MovieInfoPanel movieInfoPanel;
    private com.PA.Views.MovieListPanel movieListPanel;
    // End of variables declaration//GEN-END:variables
}
