/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.PA.Views;
import com.PA.MovieCatalog.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Costinel
 */
public class MovieListPanel extends javax.swing.JPanel 
{
    private static int kMovieProperties = 6;
    /**
     * Creates new form MovieListPanel
     */
    public MovieListPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        moviesTable = new javax.swing.JTable();

        moviesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(moviesTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable moviesTable;
    // End of variables declaration//GEN-END:variables

    public void displayMovieList(List<Movie> movieList)
    {
        int size = movieList.size();
        Object[][] data = new Object[size][kMovieProperties];
        for(int i=0; i<size; i++)
        {
            Movie m = movieList.get(i);
            
            data[i] = new Object[]{m.getName(), m.getRating() + "", m.getDirectorName(), m.getImdbID(), 
                m.getReleaseDate(), m.getFilePath()};
        }
        
        TableModel model = new DefaultTableModel(data, new Object[]{"Name", "Rating", "Director", "IMDB", 
                                                                "Release date", "File path"});
        
        this.moviesTable.setModel(model);
    }
    
    
}
